export const INIT_USER = 'INIT_USER';
export const INIT_USERS = 'INIT_USERS';
export const USERS_ONLINE = 'USERS_ONLINE';
// export const USER_LOGINS = 'USER_LOGINS';
export const SAVE_TEST_TO_USER = 'SAVE_TEST_TO_USER';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const LOADING_USER = 'LOADING_USER';
export const LOADING_USERS = 'LOADING_USERS';

export const LOADING_STATISTICS = 'LOADING_STATISTICS';
export const STATISTICS_DATA = 'STATISTICS_DATA';