export const UPDATE_TESTMENU = 'UPDATE_TESTMENU'

export const UPDATE_QUESTION_INDEX = 'UPDATE_QUESTION_INDEX'
export const INIT_FIXED_TESTS = 'INIT_FIXED_TESTS'
export const INIT_QUESTIONS = 'INIT_QUESTIONS'
export const UPDATE_TEST_QUESTIONS = 'UPDATE_TEST_QUESTIONS'

export const POPULATE_TEST = 'POPULATE_TEST'

export const INIT_IMAGES_COLLECTION = 'INIT_IMAGES_COLLECTION'